### ISSUE TITLE
PRO version of vue-paper-dashboard

### ISSUE THREAD

**Issue by bruno222** [cristijora/vue-paper-dashboard#14]
Do you have the PRO version of paper-dashboard for Vue? Tks

**Comment by cristijora** [comment]
Hi @bruno222 There is a PRO version which is pretty much read both from code perspective and documentation perspective. There is a big chance that it will be posted on creative-tim by the end of this week so stay tuned :)

**Comment by cristijora** [comment]
First PRO version is up online
https://www.creative-tim.com/product/vue-paper-dashboard-pro
