### ISSUE TITLE
Make sidebar collapsible

### ISSUE THREAD

**Issue by marcosPerezRubio** [cristijora/vue-paper-dashboard#15]
Hello!

First of all, congratulations for this awesome template!

The only thing I miss is the collapsible sidebar, I think it would be perfect to be able to do it, showing only the icons.

What do you think?

**Comment by cristijora** [comment]
@marcosPerezRubio Unfortunately this will only be available in the PRO version (which will be sold)
I have a plugin/component which is in progress https://github.com/cristijora/vue-side-bar
I will contain a couple of themes in the end but don't have a clear timeline of when it will be done yet 😄

**Comment by marcosPerezRubio** [comment]
Thanks @cristijora, another reason more to buy it!

Do you know when will be the pro version released? 

Thanks in advance

**Comment by cristijora** [comment]
Hopefully today :)

**Comment by cristijora** [comment]
@marcosPerezRubio First version is up online https://www.creative-tim.com/product/vue-paper-dashboard-pro
