### ISSUE TITLE
Unit test's fail

### ISSUE THREAD

**Issue by reustonium** [cristijora/vue-paper-dashboard#19]
It looks like there is some issue caused by sass when running the unit tests.

**Comment by cristijora** [comment]
Hi @reustonium This repo only had an outdated test and doesn't have issues when running unit tests.
If you used [vue-paper-dashboard-cli](https://github.com/cristijora/vue-paper-dashboard) to scaffold the project then you should adjust  `test/index.js` a bit.

The srcContext should contain `.vue` extensions like this:

```js
const srcContext = require.context('../../src', true, /^\.\/(?!main\.js$).+\.(js|vue)$/i)
srcContext.keys().forEach(srcContext)
```

**Comment by cristijora** [comment]
I've updated the cli repo to contain latest updates including unit tests with the official vue-test-utils. If you still have issues, let me know
