### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by zietbukuel** [cristijora/vue-paper-dashboard#20]
When I open the documentation site, I only see a white page. Nothing in it. I'm new to this theme so I was trying to read the docs so I can install it properly. Thanks.

**Comment by cristijora** [comment]
Hi @zietbukuel The documentation is based on [Docsify](https://docsify.js.org/#/quickstart) and might be related to docsify not working in all browsers.
Please try opening it in another browser or see if you get any errors in the console. A browser version and operating system would help in investigating what's the problem

**Comment by zietbukuel** [comment]
Oh I see, I tried to open the docsify website but it also doesn't work. My browser Chrome Version 61.0.3163.100 (Official Build) (64-bit).

**Comment by cristijora** [comment]
@zietbukuel Do you get any errors ? Have you tried incognito or other browsers? It may be because of some local browser configuration. Not sure why
