### ISSUE TITLE
Error in formGroupInput.vue file on run dev.

### ISSUE THREAD

**Issue by christian-quisbert** [cristijora/vue-paper-dashboard#33]
**git clone https://github.com/cristijora/vue-paper-dashboard.git
npm install 
npm run dev**

`
ERROR  Failed to compile with 1 errors                                                                                                                                                             19:44:16

 error  in ./src/components/UIComponents/Inputs/formGroupInput.vue

  ✘  http://eslint.org/docs/rules/space-before-function-paren  Missing space before function parentheses     
  src/components/UIComponents/Inputs/formGroupInput.vue:21:18
      updateValue(value) {
                    ^

  ✘  http://eslint.org/docs/rules/semi                         Extra semicolon                               
  src/components/UIComponents/Inputs/formGroupInput.vue:22:43
        this.$emit('input', String(value));
                                             ^

  ✘  http://eslint.org/docs/rules/indent                       Expected indentation of 2 spaces but found 0  
  src/components/UIComponents/Inputs/formGroupInput.vue:24:3
  }
     ^

✘ 3 problems (3 errors, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/indent
  1  http://eslint.org/docs/rules/semi
  1  http://eslint.org/docs/rules/space-before-function-paren
`

**The problem is solved, correcting the "updateValue" method of the specified file (formGroupInput.vue)**

**Comment by christian-quisbert** [comment]
Corrections:
> ✘ http://eslint.org/docs/rules/space-before-function-paren Missing space before function parentheses
src/components/UIComponents/Inputs/formGroupInput.vue:21:18
updateValue(value) {
^

Between "updateValue" and "(value)", leave a space.

> ✘ http://eslint.org/docs/rules/semi Extra semicolon
src/components/UIComponents/Inputs/formGroupInput.vue:22:43
this.$emit('input', String(value));
^

Delete the ";".

> ✘ http://eslint.org/docs/rules/indent Expected indentation of 2 spaces but found 0
src/components/UIComponents/Inputs/formGroupInput.vue:24:3
}
^

Leave 2 more spaces for that mark "}".

**Comment by hacklock** [comment]
Wow Cool !
