### ISSUE TITLE
Modal is not working good 

### ISSUE THREAD

**Issue by obelich** [cristijora/vue-paper-dashboard#9]
I add a modal Bootstrap and import bootstrap.min but the modal is show but is not usable :(

**Comment by cristijora** [comment]
First of all this project does NOT use jQuery or jQuery plugins. It only uses bootstrap css as you can see here https://github.com/cristijora/vue-paper-dashboard/blob/master/src/main.js#L16

To use a modal I suggest using pure Vue components for that. There are many good third party modal components there. You can find the in awesome-vue repo
https://github.com/vuejs/awesome-vue#overlay

Or build your own. There is an example for that in the official Vue.js documentation https://vuejs.org/v2/examples/modal.html

As a future suggestion, I don't recomend using jQuery unless you totally need it for plugins or components which don't exist for vue. Using it is, blocks you a bit using the full power of Vue and also adds to the final size of the project. Search in [awesome-vue](https://github.com/vuejs/awesome-vue). There is a lot of good stuff there!

**Comment by kikoseijo** [comment]
Install bootstrap 3,
require in JS, 

```js
require('bootstrap/dist/js/npm');
```

in your CSS add the following:

```css
.modal-backdrop {
  display: none !important;
}
```

Now you can use it.

Happy days!
